# Defining data folder structure
folder_structure:
  #data_root_folder: &BASE /home/crosslab/Desktop/Opal
  data_root_folder: &BASE /media/sz/Data/Connected_Lecturers/Opal
  raw_data_folder: &RAW !join [*BASE, /raw]
  file_folder: &FILE_FOLDER !join [*RAW, /files]
  content_folder: &CONTENT_FOLDER !join [*RAW, /content]
  processed_data_folder: &PREPROCESSED !join [*BASE, /processed]

# Global LLM Configuration (can be overridden in individual stages)
global_llm_config: &LLM_CONFIG
  base_url: "http://localhost:11434"
  embedding_model: "jina/jina-embeddings-v2-base-de"
  collection_name: "oer_connected_lecturer"
  timeout_seconds: 240
  chroma_db_folder: "chroma_db"  # ChromaDB database folder

# Global Logging Configuration
logging:
  configure_root_logger: false  # Whether to configure the root logger
  root_level: "ERROR"          # Level for root logger (if enabled)
  pipeline_level: "INFO"       # Level for pipeline-specific loggers
  
  # External logger configuration (overrides default values)
  external_loggers:
    # HTTP and network - set to CRITICAL for less noise
    httpcore: "CRITICAL"
    "httpcore.http11": "CRITICAL"
    httpx: "CRITICAL"
    urllib3: "CRITICAL"
    "urllib3.connectionpool": "CRITICAL"
    requests: "CRITICAL"
    
    # LangChain and AI - set to WARNING for important messages
    langchain: "WARNING"
    langchain_ollama: "WARNING"
    "langchain_text_splitters.base": "ERROR"
    ollama: "WARNING"
    
    # Image processing - set to WARNING
    PIL: "WARNING"
    "PIL.PngImagePlugin": "WARNING"
    
    # Unstructured - set to CRITICAL for less noise
    "unstructured.trace": "CRITICAL"

# Referencing the modules containing classes
stages_module_path:
    - ../stages/general/
    - ../stages/opal/

# Defining stages and parameters
stages:
  - name: Generate data folder structure
    class: ProvideDataFolders

  - name: Collect raw data from OPAL 
    class: CollectOPALOERdocuments
    parameters:
      repo_file_name: OPAL_repos.p
      file_name: &OPALSINGLEFILES OPAL_files.p
      json_file_name: OPAL_raw_data.json
      json_url: https://bildungsportal.sachsen.de/opal/oer/content.json
      force_run: False

  - name: Aggregate basic features from OPAL
    class: Preprocessing
    parameters: 
      file_name_input: *OPALSINGLEFILES
      file_name_output: &OPALSINGLEFILESATTRIB OPAL_files_attrib.p
      force_run: False

  - name: Download files
    class: DownloadOERFromOPAL
    parameters: 
      file_name_input: *OPALSINGLEFILESATTRIB
      file_name_output: &OPALSINGLEFILESDOWNLOADS OPAL_files_downloads.p
      file_types: ['pptx', 'pdf', 'docx', 'xlsx', 'md']
      force_run: False

  - name: Extract meta data from OPAL files
    class: MetaDataExtraction
    parameters: 
      file_name_input: *OPALSINGLEFILESATTRIB
      file_name_output: &OPALSINGLEFILESMETA OPAL_files_meta.p
      file_types: ['pptx', 'pdf', 'docx', 'xlsx', 'md']
      force_run: False

  - name: Extract content
    class: ExtractFileContent
    parameters: 
      file_name_input: *OPALSINGLEFILESATTRIB
      file_name_output: &OPALSINGLEAICONTENT OPAL_content.p
      force_run: False
      file_types: ['pptx', 'pdf', 'docx', 'xlsx', 'md']

  - name: Filter file list by content data
    class: FilterFilesByContent
    parameters:
      file_name_input: *OPALSINGLEFILESATTRIB
      file_content: *OPALSINGLEAICONTENT
      file_name_output: &OPALSINGLEFILESFILTERED OPAL_files_filtered.p
      force_run: False

  - name: Provide embeddings
    class: AIEmbeddingsGeneration
    parameters: 
      file_name_input: *OPALSINGLEFILESFILTERED
      file_name_output: &OPALCHROMAFILES OPAL_embeddings_files.p
      force_run: False
      file_types: ['pptx', 'pdf', 'docx', 'xlsx', 'md']
      
      # LLM and Vector Store Configuration
      llm_config: *LLM_CONFIG

  - name: Extract meta data from content
    class: AIMetaDataExtraction
    parameters: 
      file_name_input: *OPALSINGLEFILESFILTERED
      file_name_output: &OPALSINGLEAIMETA OPAL_ai_meta.p
      prompts_file_name: prompts.yaml
      dewey_classification_file: dewey_classification.txt
      model_name: llama3:70b
      force_run: False
      file_types: ['pptx', 'pdf', 'docx', 'xlsx', 'md']
      
      # LLM and Vector Store Configuration
      llm_config: *LLM_CONFIG
      
      # Processing mode configuration
      processing_mode:
        # Force processing: These fields are ALWAYS processed (overwrite existing data)
        force_processing:    # [] Empty list = no force processing
          - ai:affiliation
          - ai:dewey
          - ai:author     
        
        # Conditional processing: These fields are only processed if empty/missing
        conditional_processing:
          - ai:author
          - ai:keywords_gen
          - ai:title
          - ai:type
          - ai:keywords_ext
          - ai:keywords_dnb
          - ai:summary     
        
        # Skip configuration: Skip file if NO conditional fields need processing
        # AND force_processing is disabled (which it now is)
        allow_skip_when_all_conditional_filled: false  # Enable skipping when all fields are filled

  - name: Check Keywords
    class: GNDKeywordCheck
    parameters: 
      file_name_input: *OPALSINGLEAIMETA
      file_name_output: &OPALKEYWORDS OPAL_checked_keywords.p
      force_run: True
      use_llm: true         # KI-basierte Schlagwortauswahl aktivieren
      llm_model: "gemma3:27b"  # Ollama-Modell für Schlagwortauswahl
      use_full_keyword_context: true  # Alle Keywords eines Dokuments als Kontext verwenden
      use_document_metadata: true     # Zusätzliche Dokumentmetadaten als Kontext einbeziehen

  - name: Determine similarity between files
    class: DocumentSimilarity
    parameters: 
      file_name_input: *OPALSINGLEFILESFILTERED
      file_name_output: &OPALAISIMILARITY OPAL_ai_similaritiy.p
      force_run: True
      
      # Vector Store Configuration
      llm_config:
        collection_name: "oer_connected_lecturer"
