# Defining data folder stucture
folder_structure:
  #data_root_folder: &BASE ./data
  data_root_folder: &BASE /media/sz/Data/Connected_Lecturers/Opal
  raw_data_folder: &RAW !join [*BASE, /raw]
  file_folder: &FILE_FOLDER !join [*RAW, /files]
  content_folder: &CONTENT_FOLDER !join [*RAW, /content]
  processed_data_folder: &PREPROCESSED !join [*BASE, /processed]

# Referencing the modules containing modules
stages_module_path:
    - ../src/general/
    - ../src/opal/

# Defining stages and parameters
stages:
  - name: Generate data folder structure
    class: ProvideDataFolders

  - name: Collect raw data from OPAL 
    class: CollectOPALOERdocuments
    parameters:
      repo_file_name: OPAL_repos.p
      file_file_name: &OPALSINGLEFILES OPAL_files.p
      json_file_name: OPAL_raw_data.json
      json_url: https://bildungsportal.sachsen.de/opal/oer/content.json
      overwrite_json: False

  - name: Aggregate basic features from OPAL
    class: Preprocessing
    parameters: 
       file_file_name_input: *OPALSINGLEFILES
       file_file_name_output: &OPALSINGLEFILESATTRIB OPAL_files_attrib.p
       force_run: False

  - name: Download files
    class: DownloadOERFromOPAL
    parameters: 
       file_file_name_input: *OPALSINGLEFILESATTRIB
       file_file_name_output: &OPALSINGLEFILESDOWNLOADS OPAL_files_downloads.p
       file_types: ['pptx', 'pdf', 'docx', 'xlsx']
       force_run: False

  - name: Extract meta data from files
    class: MetaDataExtraction
    parameters: 
       file_file_name_input: *OPALSINGLEFILESATTRIB
       file_file_name_output: &OPALSINGLEFILESMETA OPAL_files_meta.p
       file_types: ['pptx', 'pdf', 'docx', 'xlsx']
       force_run: False

  - name: Extract content
    class: ExtractFileContent
    parameters: 
       file_file_name_input: *OPALSINGLEFILESATTRIB
       file_file_name_output: &OPALSINGLEAICONTENT OPAL_content.p
       force_run: False
       file_types: ['pptx', 'pdf', 'docx', 'xlsx']

  - name: Extract meta data from content
    class: AIMetaDataExtraction
    parameters: 
       file_file_name_input: *OPALSINGLEFILESATTRIB
       file_file_name_output: &OPALSINGLEAIMETA OPAL_ai_meta.p
       force_run: False
       file_types: ['pptx', 'pdf', 'docx', 'xlsx']

  - name: Determine similarity between files
    class: DocumentSimilarity
    parameters: 
       file_file_name_input: *OPALSINGLEAICONTENT
       file_file_name_output: &OPALSINGLESIMILARITY OPAL_similaritiy.p
       force_run: True