# Defining data folder stucture
folder_structure:
  #data_root_folder: &BASE ./data
  data_root_folder: &BASE /media/sz/Data/Connected_Lecturers/LiaScript
  raw_data_folder: &RAW !join [*BASE, /raw]
  file_folder: &FILE_FOLDER !join [*RAW, /files]
  processed_data_folder: &PREPROCESSED !join [*BASE, /processed]

# Referencing the modules containing modules
stages_module_path:
    - ../src/general/
    - ../src/liascript/

# Defining stages and parameters
stages:
  - name: Generate data folder structure
    class: ProvideDataFolders

  - name: Identify LiaScript repositories
    class: CrawlGithubForLiaScript
    parameters:
      repo_data_file_name: &REPOSITORIES_DF LiaScript_repositories.p
      force_run: False
      #internal: ['LiaScript','TUBAF-IfI-LiaScript','LiaPlayground','SebastianZug','andre-dietrich','LiaBooks','LiaTemplates','TUBAF-IUZ-LiaScript','markjjacob','HueblerPatricia']

  - name: Aggregate LiaScript files
    class: AggregateLiaScriptFiles
    parameters:
      repo_data_file_name_input: *REPOSITORIES_DF
      lia_files_name: &LIAFILES_DF LiaScript_files.p
      force_run: False

  - name: Aggregate LiaScript commits
    class: AggregateLiaScriptCommits
    parameters:
      lia_files_name_input: *LIAFILES_DF
      lia_commits_name: LiaScript_commits.p
      force_run: False

  - name: Extract LiaScript metadata
    class: ExtractLiaScriptMetadata
    parameters:
      lia_files_name_input: *LIAFILES_DF
      lia_metadata_name: LiaScript_metadata.p
      force_run: True